//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ally" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="enemy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rounding" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
public class AdvancedCrewTooltips {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "enabled")
    protected String enabled;
    @XmlAttribute(name = "ally")
    protected String ally;
    @XmlAttribute(name = "enemy")
    protected String enemy;
    @XmlAttribute(name = "rounding")
    protected Byte rounding;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the ally property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlly() {
        return ally;
    }

    /**
     * Sets the value of the ally property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlly(String value) {
        this.ally = value;
    }

    /**
     * Gets the value of the enemy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnemy() {
        return enemy;
    }

    /**
     * Sets the value of the enemy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnemy(String value) {
        this.enemy = value;
    }

    /**
     * Gets the value of the rounding property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getRounding() {
        return rounding;
    }

    /**
     * Sets the value of the rounding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setRounding(Byte value) {
        this.rounding = value;
    }

}
