//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="color"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="unvisitedTooltip"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="visitedTooltip"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="undiscoveredTooltip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="global" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="req" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "color",
    "unvisitedTooltip",
    "visitedTooltip",
    "undiscoveredTooltip"
})
public class BeaconType2 {

    protected List<Color2> color;
    protected List<UnvisitedTooltip> unvisitedTooltip;
    protected List<VisitedTooltip> visitedTooltip;
    protected List<String> undiscoveredTooltip;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "global")
    protected String global;
    @XmlAttribute(name = "req")
    protected String req;

    /**
     * Gets the value of the color property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the color property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Color2 }
     * 
     * 
     */
    public List<Color2> getColor() {
        if (color == null) {
            color = new ArrayList<Color2>();
        }
        return this.color;
    }

    /**
     * Gets the value of the unvisitedTooltip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unvisitedTooltip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnvisitedTooltip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnvisitedTooltip }
     * 
     * 
     */
    public List<UnvisitedTooltip> getUnvisitedTooltip() {
        if (unvisitedTooltip == null) {
            unvisitedTooltip = new ArrayList<UnvisitedTooltip>();
        }
        return this.unvisitedTooltip;
    }

    /**
     * Gets the value of the visitedTooltip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitedTooltip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitedTooltip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VisitedTooltip }
     * 
     * 
     */
    public List<VisitedTooltip> getVisitedTooltip() {
        if (visitedTooltip == null) {
            visitedTooltip = new ArrayList<VisitedTooltip>();
        }
        return this.visitedTooltip;
    }

    /**
     * Gets the value of the undiscoveredTooltip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the undiscoveredTooltip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUndiscoveredTooltip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUndiscoveredTooltip() {
        if (undiscoveredTooltip == null) {
            undiscoveredTooltip = new ArrayList<String>();
        }
        return this.undiscoveredTooltip;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobal(String value) {
        this.global = value;
    }

    /**
     * Gets the value of the req property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReq() {
        return req;
    }

    /**
     * Sets the value of the req property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReq(String value) {
        this.req = value;
    }

}
