//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shell" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="toxic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shellguardian" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shellmedic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shellrepair" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shellalkali" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shell",
    "toxic",
    "shellguardian",
    "shellmedic",
    "shellrepair",
    "shellalkali"
})
public class BlackList {

    @XmlElement(required = true)
    protected String shell;
    @XmlElement(required = true)
    protected String toxic;
    @XmlElement(required = true)
    protected String shellguardian;
    @XmlElement(required = true)
    protected String shellmedic;
    @XmlElement(required = true)
    protected String shellrepair;
    @XmlElement(required = true)
    protected String shellalkali;

    /**
     * Gets the value of the shell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShell() {
        return shell;
    }

    /**
     * Sets the value of the shell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShell(String value) {
        this.shell = value;
    }

    /**
     * Gets the value of the toxic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToxic() {
        return toxic;
    }

    /**
     * Sets the value of the toxic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToxic(String value) {
        this.toxic = value;
    }

    /**
     * Gets the value of the shellguardian property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellguardian() {
        return shellguardian;
    }

    /**
     * Sets the value of the shellguardian property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellguardian(String value) {
        this.shellguardian = value;
    }

    /**
     * Gets the value of the shellmedic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellmedic() {
        return shellmedic;
    }

    /**
     * Sets the value of the shellmedic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellmedic(String value) {
        this.shellmedic = value;
    }

    /**
     * Gets the value of the shellrepair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellrepair() {
        return shellrepair;
    }

    /**
     * Sets the value of the shellrepair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellrepair(String value) {
        this.shellrepair = value;
    }

    /**
     * Gets the value of the shellalkali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellalkali() {
        return shellalkali;
    }

    /**
     * Sets the value of the shellalkali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellalkali(String value) {
        this.shellalkali = value;
    }

}
