//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hpCap" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="startingScrap" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="startingFuel" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hpCap",
    "startingScrap",
    "startingFuel"
})
public class CustomShip {

    protected byte hpCap;
    protected byte startingScrap;
    protected byte startingFuel;

    /**
     * Gets the value of the hpCap property.
     * 
     */
    public byte getHpCap() {
        return hpCap;
    }

    /**
     * Sets the value of the hpCap property.
     * 
     */
    public void setHpCap(byte value) {
        this.hpCap = value;
    }

    /**
     * Gets the value of the startingScrap property.
     * 
     */
    public byte getStartingScrap() {
        return startingScrap;
    }

    /**
     * Sets the value of the startingScrap property.
     * 
     */
    public void setStartingScrap(byte value) {
        this.startingScrap = value;
    }

    /**
     * Gets the value of the startingFuel property.
     * 
     */
    public byte getStartingFuel() {
        return startingFuel;
    }

    /**
     * Sets the value of the startingFuel property.
     * 
     */
    public void setStartingFuel(byte value) {
        this.startingFuel = value;
    }

}
