//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="fightAI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="repairAI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="returnToDroneRoom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="manAI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fightAI",
    "repairAI",
    "returnToDroneRoom",
    "manAI"
})
public class DroneAI {

    protected List<String> fightAI;
    protected List<String> repairAI;
    protected List<String> returnToDroneRoom;
    protected List<String> manAI;

    /**
     * Gets the value of the fightAI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fightAI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFightAI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFightAI() {
        if (fightAI == null) {
            fightAI = new ArrayList<String>();
        }
        return this.fightAI;
    }

    /**
     * Gets the value of the repairAI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repairAI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepairAI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRepairAI() {
        if (repairAI == null) {
            repairAI = new ArrayList<String>();
        }
        return this.repairAI;
    }

    /**
     * Gets the value of the returnToDroneRoom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnToDroneRoom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnToDroneRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReturnToDroneRoom() {
        if (returnToDroneRoom == null) {
            returnToDroneRoom = new ArrayList<String>();
        }
        return this.returnToDroneRoom;
    }

    /**
     * Gets the value of the manAI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manAI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManAI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getManAI() {
        if (manAI == null) {
            manAI = new ArrayList<String>();
        }
        return this.manAI;
    }

}
