//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="hiddenAug" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="loadEvent"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="seeded" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="removeItem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="checkCargo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="noQuestText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="win"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="creditsBackground" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="creditsText" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="disableScrapScore" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="unlockShip"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="silent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="shipReq" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="secretSectorWarp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="preventQuest" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="beaconType"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="color"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="unvisitedTooltip"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="visitedTooltip"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="undiscoveredTooltip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="global" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="req" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="removeHazards" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="recursive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hiddenAug",
    "loadEvent",
    "removeItem",
    "checkCargo",
    "noQuestText",
    "win",
    "disableScrapScore",
    "unlockShip",
    "secretSectorWarp",
    "preventQuest",
    "beaconType",
    "removeHazards"
})
public class Event2 {

    protected List<String> hiddenAug;
    protected List<LoadEvent> loadEvent;
    protected List<String> removeItem;
    protected List<String> checkCargo;
    protected List<String> noQuestText;
    protected List<Win> win;
    protected List<String> disableScrapScore;
    protected List<UnlockShip> unlockShip;
    protected List<String> secretSectorWarp;
    protected List<String> preventQuest;
    protected List<BeaconType2> beaconType;
    protected List<String> removeHazards;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "recursive")
    protected String recursive;

    /**
     * Gets the value of the hiddenAug property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hiddenAug property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHiddenAug().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHiddenAug() {
        if (hiddenAug == null) {
            hiddenAug = new ArrayList<String>();
        }
        return this.hiddenAug;
    }

    /**
     * Gets the value of the loadEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loadEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoadEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoadEvent }
     * 
     * 
     */
    public List<LoadEvent> getLoadEvent() {
        if (loadEvent == null) {
            loadEvent = new ArrayList<LoadEvent>();
        }
        return this.loadEvent;
    }

    /**
     * Gets the value of the removeItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removeItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoveItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRemoveItem() {
        if (removeItem == null) {
            removeItem = new ArrayList<String>();
        }
        return this.removeItem;
    }

    /**
     * Gets the value of the checkCargo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checkCargo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCheckCargo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCheckCargo() {
        if (checkCargo == null) {
            checkCargo = new ArrayList<String>();
        }
        return this.checkCargo;
    }

    /**
     * Gets the value of the noQuestText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noQuestText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoQuestText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoQuestText() {
        if (noQuestText == null) {
            noQuestText = new ArrayList<String>();
        }
        return this.noQuestText;
    }

    /**
     * Gets the value of the win property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the win property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Win }
     * 
     * 
     */
    public List<Win> getWin() {
        if (win == null) {
            win = new ArrayList<Win>();
        }
        return this.win;
    }

    /**
     * Gets the value of the disableScrapScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disableScrapScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisableScrapScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDisableScrapScore() {
        if (disableScrapScore == null) {
            disableScrapScore = new ArrayList<String>();
        }
        return this.disableScrapScore;
    }

    /**
     * Gets the value of the unlockShip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unlockShip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnlockShip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnlockShip }
     * 
     * 
     */
    public List<UnlockShip> getUnlockShip() {
        if (unlockShip == null) {
            unlockShip = new ArrayList<UnlockShip>();
        }
        return this.unlockShip;
    }

    /**
     * Gets the value of the secretSectorWarp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secretSectorWarp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecretSectorWarp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSecretSectorWarp() {
        if (secretSectorWarp == null) {
            secretSectorWarp = new ArrayList<String>();
        }
        return this.secretSectorWarp;
    }

    /**
     * Gets the value of the preventQuest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preventQuest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreventQuest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPreventQuest() {
        if (preventQuest == null) {
            preventQuest = new ArrayList<String>();
        }
        return this.preventQuest;
    }

    /**
     * Gets the value of the beaconType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beaconType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeaconType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BeaconType2 }
     * 
     * 
     */
    public List<BeaconType2> getBeaconType() {
        if (beaconType == null) {
            beaconType = new ArrayList<BeaconType2>();
        }
        return this.beaconType;
    }

    /**
     * Gets the value of the removeHazards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removeHazards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoveHazards().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRemoveHazards() {
        if (removeHazards == null) {
            removeHazards = new ArrayList<String>();
        }
        return this.removeHazards;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the recursive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecursive() {
        return recursive;
    }

    /**
     * Sets the value of the recursive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecursive(String value) {
        this.recursive = value;
    }

}
