//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DRONE_CONTROL_COMBAT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DRONE_CONTROL_DEFENSE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DRONE_CONTROL_CREW" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dronecontrolcombat",
    "dronecontroldefense",
    "dronecontrolcrew"
})
public class FreeDrones {

    @XmlElement(name = "DRONE_CONTROL_COMBAT", required = true)
    protected String dronecontrolcombat;
    @XmlElement(name = "DRONE_CONTROL_DEFENSE", required = true)
    protected String dronecontroldefense;
    @XmlElement(name = "DRONE_CONTROL_CREW", required = true)
    protected String dronecontrolcrew;

    /**
     * Gets the value of the dronecontrolcombat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRONECONTROLCOMBAT() {
        return dronecontrolcombat;
    }

    /**
     * Sets the value of the dronecontrolcombat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRONECONTROLCOMBAT(String value) {
        this.dronecontrolcombat = value;
    }

    /**
     * Gets the value of the dronecontroldefense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRONECONTROLDEFENSE() {
        return dronecontroldefense;
    }

    /**
     * Sets the value of the dronecontroldefense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRONECONTROLDEFENSE(String value) {
        this.dronecontroldefense = value;
    }

    /**
     * Gets the value of the dronecontrolcrew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRONECONTROLCREW() {
        return dronecontrolcrew;
    }

    /**
     * Sets the value of the dronecontrolcrew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRONECONTROLCREW(String value) {
        this.dronecontrolcrew = value;
    }

}
