//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="playerText"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="align" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="enemyText"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="align" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="bossText"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="align" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "playerText",
    "enemyText",
    "bossText"
})
public class HullNumbers {

    @XmlElement(required = true)
    protected PlayerText playerText;
    @XmlElement(required = true)
    protected EnemyText enemyText;
    @XmlElement(required = true)
    protected BossText bossText;
    @XmlAttribute(name = "enabled")
    protected String enabled;

    /**
     * Gets the value of the playerText property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerText }
     *     
     */
    public PlayerText getPlayerText() {
        return playerText;
    }

    /**
     * Sets the value of the playerText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerText }
     *     
     */
    public void setPlayerText(PlayerText value) {
        this.playerText = value;
    }

    /**
     * Gets the value of the enemyText property.
     * 
     * @return
     *     possible object is
     *     {@link EnemyText }
     *     
     */
    public EnemyText getEnemyText() {
        return enemyText;
    }

    /**
     * Sets the value of the enemyText property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnemyText }
     *     
     */
    public void setEnemyText(EnemyText value) {
        this.enemyText = value;
    }

    /**
     * Gets the value of the bossText property.
     * 
     * @return
     *     possible object is
     *     {@link BossText }
     *     
     */
    public BossText getBossText() {
        return bossText;
    }

    /**
     * Sets the value of the bossText property.
     * 
     * @param value
     *     allowed object is
     *     {@link BossText }
     *     
     */
    public void setBossText(BossText value) {
        this.bossText = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

}
