//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="cooldown" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="jumpCooldown" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="powerSounds"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="powerSound" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="finishSound" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="sound" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="deathSound" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="enemy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="friendlyFire" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shipFriendlyFire" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="buttonText"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tooltip"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cooldownColor"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="effectAnim" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="crewHealth" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="selfHealth" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="temporaryEffect"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="cooldownColor"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="statBoosts"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="statBoost" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                                       &lt;element name="boostType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                                       &lt;element name="shipTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="crewTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="affectsSelf" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="whiteList"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="hatch" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="spider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="weaver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="queen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/choice&gt;
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="moveSpeedMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="finishSounds"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="finishSound" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="animSheet"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="baseVisible" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="allDamageTakenMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="isTelepathic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="effectAnim" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="damageMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="fireDamageMultiplier" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="suffocationModifier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="repairSpeed" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="sabotageSpeedMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="damageTakenMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="healAmount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="damageEnemiesAmount" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="healCrewAmount" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="invulnerable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="canFight" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="canSabotage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="canPhaseThroughDoors" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="canRepair" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="detectsLifeforms" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="controllable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="canMan" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="bonusPower" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="oxygenChangeSpeed" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="hackDoors" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="req"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="enemyShip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="systemInRoom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="damaged" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="enemyInRoom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="inCombat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="minHealth" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="maxHealth" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="hasClonebay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="friendlyInRoom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="playerShip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="aiDisabled" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sysDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="persDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="fireChance" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="stun" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="breachChance" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="activateWhenReady"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="enemiesOnly" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="animFrame" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="lockdown" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="transformRace" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ion" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="stunChance" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="damage" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="enemyHealth" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cooldown",
    "jumpCooldown",
    "powerSounds",
    "friendlyFire",
    "shipFriendlyFire",
    "buttonText",
    "tooltip",
    "cooldownColor",
    "effectAnim",
    "crewHealth",
    "selfHealth",
    "temporaryEffect",
    "req",
    "sysDamage",
    "persDamage",
    "fireChance",
    "stun",
    "breachChance",
    "activateWhenReady",
    "animFrame",
    "lockdown",
    "transformRace",
    "ion",
    "stunChance",
    "damage",
    "enemyHealth"
})
public class PowerEffect {

    @XmlElement(type = Short.class)
    protected List<Short> cooldown;
    protected List<String> jumpCooldown;
    protected List<PowerSounds> powerSounds;
    protected List<String> friendlyFire;
    protected List<String> shipFriendlyFire;
    protected List<ButtonText> buttonText;
    protected List<Tooltip> tooltip;
    protected List<CooldownColor> cooldownColor;
    protected List<String> effectAnim;
    @XmlElement(type = Short.class)
    protected List<Short> crewHealth;
    @XmlElement(type = Short.class)
    protected List<Short> selfHealth;
    protected List<TemporaryEffect> temporaryEffect;
    protected List<Req3> req;
    @XmlElement(type = Byte.class)
    protected List<Byte> sysDamage;
    @XmlElement(type = Byte.class)
    protected List<Byte> persDamage;
    @XmlElement(type = Byte.class)
    protected List<Byte> fireChance;
    @XmlElement(type = Byte.class)
    protected List<Byte> stun;
    @XmlElement(type = Byte.class)
    protected List<Byte> breachChance;
    protected List<ActivateWhenReady> activateWhenReady;
    @XmlElement(type = Byte.class)
    protected List<Byte> animFrame;
    protected List<String> lockdown;
    protected List<String> transformRace;
    @XmlElement(type = Byte.class)
    protected List<Byte> ion;
    @XmlElement(type = Byte.class)
    protected List<Byte> stunChance;
    @XmlElement(type = Byte.class)
    protected List<Byte> damage;
    @XmlElement(type = Byte.class)
    protected List<Byte> enemyHealth;

    /**
     * Gets the value of the cooldown property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cooldown property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCooldown().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getCooldown() {
        if (cooldown == null) {
            cooldown = new ArrayList<Short>();
        }
        return this.cooldown;
    }

    /**
     * Gets the value of the jumpCooldown property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jumpCooldown property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJumpCooldown().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getJumpCooldown() {
        if (jumpCooldown == null) {
            jumpCooldown = new ArrayList<String>();
        }
        return this.jumpCooldown;
    }

    /**
     * Gets the value of the powerSounds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the powerSounds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPowerSounds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PowerSounds }
     * 
     * 
     */
    public List<PowerSounds> getPowerSounds() {
        if (powerSounds == null) {
            powerSounds = new ArrayList<PowerSounds>();
        }
        return this.powerSounds;
    }

    /**
     * Gets the value of the friendlyFire property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the friendlyFire property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFriendlyFire().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFriendlyFire() {
        if (friendlyFire == null) {
            friendlyFire = new ArrayList<String>();
        }
        return this.friendlyFire;
    }

    /**
     * Gets the value of the shipFriendlyFire property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipFriendlyFire property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipFriendlyFire().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getShipFriendlyFire() {
        if (shipFriendlyFire == null) {
            shipFriendlyFire = new ArrayList<String>();
        }
        return this.shipFriendlyFire;
    }

    /**
     * Gets the value of the buttonText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buttonText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getButtonText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ButtonText }
     * 
     * 
     */
    public List<ButtonText> getButtonText() {
        if (buttonText == null) {
            buttonText = new ArrayList<ButtonText>();
        }
        return this.buttonText;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tooltip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTooltip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tooltip }
     * 
     * 
     */
    public List<Tooltip> getTooltip() {
        if (tooltip == null) {
            tooltip = new ArrayList<Tooltip>();
        }
        return this.tooltip;
    }

    /**
     * Gets the value of the cooldownColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cooldownColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCooldownColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CooldownColor }
     * 
     * 
     */
    public List<CooldownColor> getCooldownColor() {
        if (cooldownColor == null) {
            cooldownColor = new ArrayList<CooldownColor>();
        }
        return this.cooldownColor;
    }

    /**
     * Gets the value of the effectAnim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectAnim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectAnim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEffectAnim() {
        if (effectAnim == null) {
            effectAnim = new ArrayList<String>();
        }
        return this.effectAnim;
    }

    /**
     * Gets the value of the crewHealth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crewHealth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrewHealth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getCrewHealth() {
        if (crewHealth == null) {
            crewHealth = new ArrayList<Short>();
        }
        return this.crewHealth;
    }

    /**
     * Gets the value of the selfHealth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selfHealth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelfHealth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getSelfHealth() {
        if (selfHealth == null) {
            selfHealth = new ArrayList<Short>();
        }
        return this.selfHealth;
    }

    /**
     * Gets the value of the temporaryEffect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the temporaryEffect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemporaryEffect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemporaryEffect }
     * 
     * 
     */
    public List<TemporaryEffect> getTemporaryEffect() {
        if (temporaryEffect == null) {
            temporaryEffect = new ArrayList<TemporaryEffect>();
        }
        return this.temporaryEffect;
    }

    /**
     * Gets the value of the req property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the req property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Req3 }
     * 
     * 
     */
    public List<Req3> getReq() {
        if (req == null) {
            req = new ArrayList<Req3>();
        }
        return this.req;
    }

    /**
     * Gets the value of the sysDamage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sysDamage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSysDamage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getSysDamage() {
        if (sysDamage == null) {
            sysDamage = new ArrayList<Byte>();
        }
        return this.sysDamage;
    }

    /**
     * Gets the value of the persDamage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the persDamage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersDamage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getPersDamage() {
        if (persDamage == null) {
            persDamage = new ArrayList<Byte>();
        }
        return this.persDamage;
    }

    /**
     * Gets the value of the fireChance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fireChance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFireChance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getFireChance() {
        if (fireChance == null) {
            fireChance = new ArrayList<Byte>();
        }
        return this.fireChance;
    }

    /**
     * Gets the value of the stun property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stun property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStun().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getStun() {
        if (stun == null) {
            stun = new ArrayList<Byte>();
        }
        return this.stun;
    }

    /**
     * Gets the value of the breachChance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the breachChance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBreachChance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getBreachChance() {
        if (breachChance == null) {
            breachChance = new ArrayList<Byte>();
        }
        return this.breachChance;
    }

    /**
     * Gets the value of the activateWhenReady property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activateWhenReady property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivateWhenReady().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivateWhenReady }
     * 
     * 
     */
    public List<ActivateWhenReady> getActivateWhenReady() {
        if (activateWhenReady == null) {
            activateWhenReady = new ArrayList<ActivateWhenReady>();
        }
        return this.activateWhenReady;
    }

    /**
     * Gets the value of the animFrame property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the animFrame property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnimFrame().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getAnimFrame() {
        if (animFrame == null) {
            animFrame = new ArrayList<Byte>();
        }
        return this.animFrame;
    }

    /**
     * Gets the value of the lockdown property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lockdown property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLockdown().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLockdown() {
        if (lockdown == null) {
            lockdown = new ArrayList<String>();
        }
        return this.lockdown;
    }

    /**
     * Gets the value of the transformRace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformRace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransformRace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTransformRace() {
        if (transformRace == null) {
            transformRace = new ArrayList<String>();
        }
        return this.transformRace;
    }

    /**
     * Gets the value of the ion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getIon() {
        if (ion == null) {
            ion = new ArrayList<Byte>();
        }
        return this.ion;
    }

    /**
     * Gets the value of the stunChance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stunChance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStunChance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getStunChance() {
        if (stunChance == null) {
            stunChance = new ArrayList<Byte>();
        }
        return this.stunChance;
    }

    /**
     * Gets the value of the damage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the damage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDamage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getDamage() {
        if (damage == null) {
            damage = new ArrayList<Byte>();
        }
        return this.damage;
    }

    /**
     * Gets the value of the enemyHealth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enemyHealth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnemyHealth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getEnemyHealth() {
        if (enemyHealth == null) {
            enemyHealth = new ArrayList<Byte>();
        }
        return this.enemyHealth;
    }

}
