//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="enemyShip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="systemInRoom"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="damaged" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="enemyInRoom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="inCombat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="minHealth" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="maxHealth" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="hasClonebay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="friendlyInRoom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="playerShip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="aiDisabled" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enemyShip",
    "systemInRoom",
    "enemyInRoom",
    "inCombat",
    "minHealth",
    "maxHealth",
    "hasClonebay",
    "friendlyInRoom",
    "playerShip",
    "aiDisabled"
})
public class Req3 {

    protected List<String> enemyShip;
    protected List<SystemInRoom> systemInRoom;
    protected List<String> enemyInRoom;
    protected List<String> inCombat;
    @XmlElement(type = Byte.class)
    protected List<Byte> minHealth;
    @XmlElement(type = Byte.class)
    protected List<Byte> maxHealth;
    protected List<String> hasClonebay;
    protected List<String> friendlyInRoom;
    protected List<String> playerShip;
    protected List<String> aiDisabled;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the enemyShip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enemyShip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnemyShip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEnemyShip() {
        if (enemyShip == null) {
            enemyShip = new ArrayList<String>();
        }
        return this.enemyShip;
    }

    /**
     * Gets the value of the systemInRoom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemInRoom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemInRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemInRoom }
     * 
     * 
     */
    public List<SystemInRoom> getSystemInRoom() {
        if (systemInRoom == null) {
            systemInRoom = new ArrayList<SystemInRoom>();
        }
        return this.systemInRoom;
    }

    /**
     * Gets the value of the enemyInRoom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enemyInRoom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnemyInRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEnemyInRoom() {
        if (enemyInRoom == null) {
            enemyInRoom = new ArrayList<String>();
        }
        return this.enemyInRoom;
    }

    /**
     * Gets the value of the inCombat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inCombat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInCombat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInCombat() {
        if (inCombat == null) {
            inCombat = new ArrayList<String>();
        }
        return this.inCombat;
    }

    /**
     * Gets the value of the minHealth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the minHealth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMinHealth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getMinHealth() {
        if (minHealth == null) {
            minHealth = new ArrayList<Byte>();
        }
        return this.minHealth;
    }

    /**
     * Gets the value of the maxHealth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the maxHealth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaxHealth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getMaxHealth() {
        if (maxHealth == null) {
            maxHealth = new ArrayList<Byte>();
        }
        return this.maxHealth;
    }

    /**
     * Gets the value of the hasClonebay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hasClonebay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasClonebay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHasClonebay() {
        if (hasClonebay == null) {
            hasClonebay = new ArrayList<String>();
        }
        return this.hasClonebay;
    }

    /**
     * Gets the value of the friendlyInRoom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the friendlyInRoom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFriendlyInRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFriendlyInRoom() {
        if (friendlyInRoom == null) {
            friendlyInRoom = new ArrayList<String>();
        }
        return this.friendlyInRoom;
    }

    /**
     * Gets the value of the playerShip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the playerShip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayerShip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlayerShip() {
        if (playerShip == null) {
            playerShip = new ArrayList<String>();
        }
        return this.playerShip;
    }

    /**
     * Gets the value of the aiDisabled property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aiDisabled property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAiDisabled().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAiDisabled() {
        if (aiDisabled == null) {
            aiDisabled = new ArrayList<String>();
        }
        return this.aiDisabled;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
