//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="exitBeacon" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="event" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="nebulaEvent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="rebelEvent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rebelBeacon" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="event" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="removeFirstBeaconNebula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="preventQuest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="beaconType" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="color"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="unvisitedTooltip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="visitedTooltip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="global" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exitBeacon",
    "rebelBeacon",
    "removeFirstBeaconNebula",
    "preventQuest",
    "beaconType"
})
public class Sector {

    protected ExitBeacon exitBeacon;
    protected RebelBeacon rebelBeacon;
    protected String removeFirstBeaconNebula;
    protected String preventQuest;
    protected BeaconType beaconType;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the exitBeacon property.
     * 
     * @return
     *     possible object is
     *     {@link ExitBeacon }
     *     
     */
    public ExitBeacon getExitBeacon() {
        return exitBeacon;
    }

    /**
     * Sets the value of the exitBeacon property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExitBeacon }
     *     
     */
    public void setExitBeacon(ExitBeacon value) {
        this.exitBeacon = value;
    }

    /**
     * Gets the value of the rebelBeacon property.
     * 
     * @return
     *     possible object is
     *     {@link RebelBeacon }
     *     
     */
    public RebelBeacon getRebelBeacon() {
        return rebelBeacon;
    }

    /**
     * Sets the value of the rebelBeacon property.
     * 
     * @param value
     *     allowed object is
     *     {@link RebelBeacon }
     *     
     */
    public void setRebelBeacon(RebelBeacon value) {
        this.rebelBeacon = value;
    }

    /**
     * Gets the value of the removeFirstBeaconNebula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveFirstBeaconNebula() {
        return removeFirstBeaconNebula;
    }

    /**
     * Sets the value of the removeFirstBeaconNebula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveFirstBeaconNebula(String value) {
        this.removeFirstBeaconNebula = value;
    }

    /**
     * Gets the value of the preventQuest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreventQuest() {
        return preventQuest;
    }

    /**
     * Sets the value of the preventQuest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreventQuest(String value) {
        this.preventQuest = value;
    }

    /**
     * Gets the value of the beaconType property.
     * 
     * @return
     *     possible object is
     *     {@link BeaconType }
     *     
     */
    public BeaconType getBeaconType() {
        return beaconType;
    }

    /**
     * Sets the value of the beaconType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeaconType }
     *     
     */
    public void setBeaconType(BeaconType value) {
        this.beaconType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
