//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="boostType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="shipTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="crewTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="droneTarget" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="affectsSelf" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="systemPowerDependency" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="oxygen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="battery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="systemPowerScaling" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="noSys" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="hackedSys" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="noPwr" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="onePwr" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="twoPwr" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="threePwr" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="morePwr" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maxStacks" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="whiteList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="hatch" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="spider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="weaver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "boostType",
    "value",
    "amount",
    "shipTarget",
    "crewTarget",
    "droneTarget",
    "affectsSelf",
    "systemPowerDependency",
    "systemPowerScaling",
    "maxStacks",
    "priority",
    "whiteList"
})
public class StatBoost3 {

    @XmlElement(required = true)
    protected String boostType;
    protected String value;
    protected Float amount;
    @XmlElement(required = true)
    protected String shipTarget;
    @XmlElement(required = true)
    protected String crewTarget;
    protected String droneTarget;
    protected String affectsSelf;
    protected SystemPowerDependency2 systemPowerDependency;
    protected SystemPowerScaling2 systemPowerScaling;
    protected Byte maxStacks;
    protected Short priority;
    protected WhiteList3 whiteList;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the boostType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoostType() {
        return boostType;
    }

    /**
     * Sets the value of the boostType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoostType(String value) {
        this.boostType = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAmount(Float value) {
        this.amount = value;
    }

    /**
     * Gets the value of the shipTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipTarget() {
        return shipTarget;
    }

    /**
     * Sets the value of the shipTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipTarget(String value) {
        this.shipTarget = value;
    }

    /**
     * Gets the value of the crewTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrewTarget() {
        return crewTarget;
    }

    /**
     * Sets the value of the crewTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrewTarget(String value) {
        this.crewTarget = value;
    }

    /**
     * Gets the value of the droneTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDroneTarget() {
        return droneTarget;
    }

    /**
     * Sets the value of the droneTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDroneTarget(String value) {
        this.droneTarget = value;
    }

    /**
     * Gets the value of the affectsSelf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffectsSelf() {
        return affectsSelf;
    }

    /**
     * Sets the value of the affectsSelf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffectsSelf(String value) {
        this.affectsSelf = value;
    }

    /**
     * Gets the value of the systemPowerDependency property.
     * 
     * @return
     *     possible object is
     *     {@link SystemPowerDependency2 }
     *     
     */
    public SystemPowerDependency2 getSystemPowerDependency() {
        return systemPowerDependency;
    }

    /**
     * Sets the value of the systemPowerDependency property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemPowerDependency2 }
     *     
     */
    public void setSystemPowerDependency(SystemPowerDependency2 value) {
        this.systemPowerDependency = value;
    }

    /**
     * Gets the value of the systemPowerScaling property.
     * 
     * @return
     *     possible object is
     *     {@link SystemPowerScaling2 }
     *     
     */
    public SystemPowerScaling2 getSystemPowerScaling() {
        return systemPowerScaling;
    }

    /**
     * Sets the value of the systemPowerScaling property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemPowerScaling2 }
     *     
     */
    public void setSystemPowerScaling(SystemPowerScaling2 value) {
        this.systemPowerScaling = value;
    }

    /**
     * Gets the value of the maxStacks property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMaxStacks() {
        return maxStacks;
    }

    /**
     * Sets the value of the maxStacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMaxStacks(Byte value) {
        this.maxStacks = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPriority(Short value) {
        this.priority = value;
    }

    /**
     * Gets the value of the whiteList property.
     * 
     * @return
     *     possible object is
     *     {@link WhiteList3 }
     *     
     */
    public WhiteList3 getWhiteList() {
        return whiteList;
    }

    /**
     * Sets the value of the whiteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhiteList3 }
     *     
     */
    public void setWhiteList(WhiteList3 value) {
        this.whiteList = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
