//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="boostType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="shipTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="crewTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "boostType",
    "amount",
    "shipTarget",
    "crewTarget",
    "priority"
})
public class StatBoost {

    @XmlElement(required = true)
    protected String boostType;
    protected float amount;
    @XmlElement(required = true)
    protected String shipTarget;
    @XmlElement(required = true)
    protected String crewTarget;
    protected byte priority;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the boostType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoostType() {
        return boostType;
    }

    /**
     * Sets the value of the boostType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoostType(String value) {
        this.boostType = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public float getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(float value) {
        this.amount = value;
    }

    /**
     * Gets the value of the shipTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipTarget() {
        return shipTarget;
    }

    /**
     * Sets the value of the shipTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipTarget(String value) {
        this.shipTarget = value;
    }

    /**
     * Gets the value of the crewTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrewTarget() {
        return crewTarget;
    }

    /**
     * Sets the value of the crewTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrewTarget(String value) {
        this.crewTarget = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public byte getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(byte value) {
        this.priority = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
