//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="cooldownColor"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="r" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="statBoosts"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="statBoost" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                             &lt;element name="boostType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                             &lt;element name="shipTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="crewTarget" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="affectsSelf" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="whiteList"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="hatch" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="spider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="weaver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="queen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="moveSpeedMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="finishSounds"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="finishSound" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="animSheet"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="baseVisible" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="allDamageTakenMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="isTelepathic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="effectAnim" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="damageMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="fireDamageMultiplier" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="suffocationModifier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="repairSpeed" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="sabotageSpeedMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="damageTakenMultiplier" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="healAmount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="damageEnemiesAmount" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="healCrewAmount" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="invulnerable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="canFight" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="canSabotage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="canPhaseThroughDoors" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="canRepair" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="detectsLifeforms" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="controllable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="canMan" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bonusPower" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="oxygenChangeSpeed" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="hackDoors" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "duration",
    "cooldownColor",
    "statBoosts",
    "moveSpeedMultiplier",
    "finishSounds",
    "animSheet",
    "allDamageTakenMultiplier",
    "isTelepathic",
    "effectAnim",
    "damageMultiplier",
    "fireDamageMultiplier",
    "suffocationModifier",
    "repairSpeed",
    "sabotageSpeedMultiplier",
    "damageTakenMultiplier",
    "healAmount",
    "damageEnemiesAmount",
    "healCrewAmount",
    "invulnerable",
    "canFight",
    "canSabotage",
    "canPhaseThroughDoors",
    "canRepair",
    "detectsLifeforms",
    "controllable",
    "canMan",
    "bonusPower",
    "oxygenChangeSpeed",
    "hackDoors"
})
public class TemporaryEffect {

    @XmlElement(type = Byte.class)
    protected List<Byte> duration;
    protected List<CooldownColor2> cooldownColor;
    protected List<StatBoosts2> statBoosts;
    @XmlElement(type = Float.class)
    protected List<Float> moveSpeedMultiplier;
    protected List<FinishSounds> finishSounds;
    protected List<AnimSheet> animSheet;
    @XmlElement(type = Float.class)
    protected List<Float> allDamageTakenMultiplier;
    protected List<String> isTelepathic;
    protected List<String> effectAnim;
    @XmlElement(type = Float.class)
    protected List<Float> damageMultiplier;
    @XmlElement(type = Byte.class)
    protected List<Byte> fireDamageMultiplier;
    @XmlElement(type = Float.class)
    protected List<Float> suffocationModifier;
    @XmlElement(type = Float.class)
    protected List<Float> repairSpeed;
    @XmlElement(type = Float.class)
    protected List<Float> sabotageSpeedMultiplier;
    @XmlElement(type = Float.class)
    protected List<Float> damageTakenMultiplier;
    @XmlElement(type = Float.class)
    protected List<Float> healAmount;
    @XmlElement(type = Byte.class)
    protected List<Byte> damageEnemiesAmount;
    @XmlElement(type = Byte.class)
    protected List<Byte> healCrewAmount;
    protected List<String> invulnerable;
    protected List<String> canFight;
    protected List<String> canSabotage;
    protected List<String> canPhaseThroughDoors;
    protected List<String> canRepair;
    protected List<String> detectsLifeforms;
    protected List<String> controllable;
    protected List<String> canMan;
    @XmlElement(type = Byte.class)
    protected List<Byte> bonusPower;
    @XmlElement(type = Byte.class)
    protected List<Byte> oxygenChangeSpeed;
    protected List<String> hackDoors;

    /**
     * Gets the value of the duration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the duration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDuration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getDuration() {
        if (duration == null) {
            duration = new ArrayList<Byte>();
        }
        return this.duration;
    }

    /**
     * Gets the value of the cooldownColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cooldownColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCooldownColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CooldownColor2 }
     * 
     * 
     */
    public List<CooldownColor2> getCooldownColor() {
        if (cooldownColor == null) {
            cooldownColor = new ArrayList<CooldownColor2>();
        }
        return this.cooldownColor;
    }

    /**
     * Gets the value of the statBoosts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statBoosts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatBoosts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatBoosts2 }
     * 
     * 
     */
    public List<StatBoosts2> getStatBoosts() {
        if (statBoosts == null) {
            statBoosts = new ArrayList<StatBoosts2>();
        }
        return this.statBoosts;
    }

    /**
     * Gets the value of the moveSpeedMultiplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moveSpeedMultiplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoveSpeedMultiplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getMoveSpeedMultiplier() {
        if (moveSpeedMultiplier == null) {
            moveSpeedMultiplier = new ArrayList<Float>();
        }
        return this.moveSpeedMultiplier;
    }

    /**
     * Gets the value of the finishSounds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the finishSounds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinishSounds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinishSounds }
     * 
     * 
     */
    public List<FinishSounds> getFinishSounds() {
        if (finishSounds == null) {
            finishSounds = new ArrayList<FinishSounds>();
        }
        return this.finishSounds;
    }

    /**
     * Gets the value of the animSheet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the animSheet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnimSheet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnimSheet }
     * 
     * 
     */
    public List<AnimSheet> getAnimSheet() {
        if (animSheet == null) {
            animSheet = new ArrayList<AnimSheet>();
        }
        return this.animSheet;
    }

    /**
     * Gets the value of the allDamageTakenMultiplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allDamageTakenMultiplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllDamageTakenMultiplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getAllDamageTakenMultiplier() {
        if (allDamageTakenMultiplier == null) {
            allDamageTakenMultiplier = new ArrayList<Float>();
        }
        return this.allDamageTakenMultiplier;
    }

    /**
     * Gets the value of the isTelepathic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isTelepathic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsTelepathic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIsTelepathic() {
        if (isTelepathic == null) {
            isTelepathic = new ArrayList<String>();
        }
        return this.isTelepathic;
    }

    /**
     * Gets the value of the effectAnim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectAnim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectAnim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEffectAnim() {
        if (effectAnim == null) {
            effectAnim = new ArrayList<String>();
        }
        return this.effectAnim;
    }

    /**
     * Gets the value of the damageMultiplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the damageMultiplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDamageMultiplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getDamageMultiplier() {
        if (damageMultiplier == null) {
            damageMultiplier = new ArrayList<Float>();
        }
        return this.damageMultiplier;
    }

    /**
     * Gets the value of the fireDamageMultiplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fireDamageMultiplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFireDamageMultiplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getFireDamageMultiplier() {
        if (fireDamageMultiplier == null) {
            fireDamageMultiplier = new ArrayList<Byte>();
        }
        return this.fireDamageMultiplier;
    }

    /**
     * Gets the value of the suffocationModifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the suffocationModifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuffocationModifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getSuffocationModifier() {
        if (suffocationModifier == null) {
            suffocationModifier = new ArrayList<Float>();
        }
        return this.suffocationModifier;
    }

    /**
     * Gets the value of the repairSpeed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repairSpeed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepairSpeed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getRepairSpeed() {
        if (repairSpeed == null) {
            repairSpeed = new ArrayList<Float>();
        }
        return this.repairSpeed;
    }

    /**
     * Gets the value of the sabotageSpeedMultiplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sabotageSpeedMultiplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSabotageSpeedMultiplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getSabotageSpeedMultiplier() {
        if (sabotageSpeedMultiplier == null) {
            sabotageSpeedMultiplier = new ArrayList<Float>();
        }
        return this.sabotageSpeedMultiplier;
    }

    /**
     * Gets the value of the damageTakenMultiplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the damageTakenMultiplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDamageTakenMultiplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getDamageTakenMultiplier() {
        if (damageTakenMultiplier == null) {
            damageTakenMultiplier = new ArrayList<Float>();
        }
        return this.damageTakenMultiplier;
    }

    /**
     * Gets the value of the healAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the healAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHealAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getHealAmount() {
        if (healAmount == null) {
            healAmount = new ArrayList<Float>();
        }
        return this.healAmount;
    }

    /**
     * Gets the value of the damageEnemiesAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the damageEnemiesAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDamageEnemiesAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getDamageEnemiesAmount() {
        if (damageEnemiesAmount == null) {
            damageEnemiesAmount = new ArrayList<Byte>();
        }
        return this.damageEnemiesAmount;
    }

    /**
     * Gets the value of the healCrewAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the healCrewAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHealCrewAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getHealCrewAmount() {
        if (healCrewAmount == null) {
            healCrewAmount = new ArrayList<Byte>();
        }
        return this.healCrewAmount;
    }

    /**
     * Gets the value of the invulnerable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invulnerable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvulnerable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInvulnerable() {
        if (invulnerable == null) {
            invulnerable = new ArrayList<String>();
        }
        return this.invulnerable;
    }

    /**
     * Gets the value of the canFight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canFight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanFight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCanFight() {
        if (canFight == null) {
            canFight = new ArrayList<String>();
        }
        return this.canFight;
    }

    /**
     * Gets the value of the canSabotage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canSabotage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanSabotage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCanSabotage() {
        if (canSabotage == null) {
            canSabotage = new ArrayList<String>();
        }
        return this.canSabotage;
    }

    /**
     * Gets the value of the canPhaseThroughDoors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canPhaseThroughDoors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanPhaseThroughDoors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCanPhaseThroughDoors() {
        if (canPhaseThroughDoors == null) {
            canPhaseThroughDoors = new ArrayList<String>();
        }
        return this.canPhaseThroughDoors;
    }

    /**
     * Gets the value of the canRepair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canRepair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanRepair().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCanRepair() {
        if (canRepair == null) {
            canRepair = new ArrayList<String>();
        }
        return this.canRepair;
    }

    /**
     * Gets the value of the detectsLifeforms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detectsLifeforms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetectsLifeforms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDetectsLifeforms() {
        if (detectsLifeforms == null) {
            detectsLifeforms = new ArrayList<String>();
        }
        return this.detectsLifeforms;
    }

    /**
     * Gets the value of the controllable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controllable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControllable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getControllable() {
        if (controllable == null) {
            controllable = new ArrayList<String>();
        }
        return this.controllable;
    }

    /**
     * Gets the value of the canMan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canMan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanMan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCanMan() {
        if (canMan == null) {
            canMan = new ArrayList<String>();
        }
        return this.canMan;
    }

    /**
     * Gets the value of the bonusPower property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bonusPower property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBonusPower().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getBonusPower() {
        if (bonusPower == null) {
            bonusPower = new ArrayList<Byte>();
        }
        return this.bonusPower;
    }

    /**
     * Gets the value of the oxygenChangeSpeed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oxygenChangeSpeed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOxygenChangeSpeed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Byte }
     * 
     * 
     */
    public List<Byte> getOxygenChangeSpeed() {
        if (oxygenChangeSpeed == null) {
            oxygenChangeSpeed = new ArrayList<Byte>();
        }
        return this.oxygenChangeSpeed;
    }

    /**
     * Gets the value of the hackDoors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hackDoors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHackDoors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHackDoors() {
        if (hackDoors == null) {
            hackDoors = new ArrayList<String>();
        }
        return this.hackDoors;
    }

}
