//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="splashImages"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="splashImage" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="center" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="logo_x" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *       &lt;attribute name="logo_y" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "splashImages"
})
public class TitleScreen {

    @XmlElement(required = true)
    protected SplashImages splashImages;
    @XmlAttribute(name = "logo_x")
    protected Short logoX;
    @XmlAttribute(name = "logo_y")
    protected Byte logoY;
    @XmlAttribute(name = "enabled")
    protected String enabled;

    /**
     * Gets the value of the splashImages property.
     * 
     * @return
     *     possible object is
     *     {@link SplashImages }
     *     
     */
    public SplashImages getSplashImages() {
        return splashImages;
    }

    /**
     * Sets the value of the splashImages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplashImages }
     *     
     */
    public void setSplashImages(SplashImages value) {
        this.splashImages = value;
    }

    /**
     * Gets the value of the logoX property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getLogoX() {
        return logoX;
    }

    /**
     * Sets the value of the logoX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setLogoX(Short value) {
        this.logoX = value;
    }

    /**
     * Gets the value of the logoY property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getLogoY() {
        return logoY;
    }

    /**
     * Sets the value of the logoY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setLogoY(Byte value) {
        this.logoY = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

}
