//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="human" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="medic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="engineer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="soldier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mfk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="detective" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tully" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jerry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jerryg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ponyj" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ponycj" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="engi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="separatist" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="separatistblur" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="defend" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="turzil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="monk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bomber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="radical" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="peace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="deathless" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orchid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="chieftain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mantis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="freemantis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="suzerain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="warlord" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bishop" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="outcast" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="commando" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="crusader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cultist" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lord" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="symbiote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="crystal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sentinel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ruwen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="slug" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="snail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sabo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ranger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sylvan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nights" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="slocknog" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="shell" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="shellmedic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="shellrepair" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="shellguardian" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="toxic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="shellalkali" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="anaerobic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="welder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eater" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="augmented" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="anointed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phantom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phantomalpha" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="goul" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="goulalpha" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="marealpha" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="wraith" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="wraithalpha" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reaper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bloblarge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blob" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobancient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobcrystal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobfreemantis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobhuman" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bloblizard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobmantis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobpony" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobqueen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobrock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobsalt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobshell" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobslug" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobspider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bloborchid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="techno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technoancient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technoengi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technoavatar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technolanius" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technobattle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technobattle2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technoboarderion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technorepair" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technodoctor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technomanning" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technorecon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technoatom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technodirector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technomender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technoroomba" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="technoa55" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blobswarm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hatch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="spider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="weaver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="queen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ancient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="royal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="traveler" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="avatar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="avatara" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="avatarroyal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="avatarroyala" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "human",
    "medic",
    "engineer",
    "soldier",
    "mfk",
    "detective",
    "tully",
    "jerry",
    "jerryg",
    "ponyj",
    "ponycj",
    "engi",
    "separatist",
    "separatistblur",
    "defend",
    "turzil",
    "energy",
    "monk",
    "bomber",
    "radical",
    "peace",
    "deathless",
    "orchid",
    "chieftain",
    "mantis",
    "freemantis",
    "suzerain",
    "warlord",
    "bishop",
    "rock",
    "outcast",
    "commando",
    "crusader",
    "cultist",
    "lord",
    "symbiote",
    "crystal",
    "sentinel",
    "ruwen",
    "slug",
    "snail",
    "sabo",
    "ranger",
    "sylvan",
    "nights",
    "slocknog",
    "shell",
    "shellmedic",
    "shellrepair",
    "shellguardian",
    "toxic",
    "shellalkali",
    "anaerobic",
    "welder",
    "eater",
    "augmented",
    "anointed",
    "phantom",
    "phantomalpha",
    "goul",
    "goulalpha",
    "mare",
    "marealpha",
    "wraith",
    "wraithalpha",
    "reaper",
    "bloblarge",
    "blob",
    "blobancient",
    "blobcrystal",
    "blobfreemantis",
    "blobhuman",
    "bloblizard",
    "blobmantis",
    "blobpony",
    "blobqueen",
    "blobrock",
    "blobsalt",
    "blobshell",
    "blobslug",
    "blobspider",
    "bloborchid",
    "techno",
    "technoancient",
    "technoengi",
    "technoavatar",
    "technolanius",
    "technobattle",
    "technobattle2",
    "technoboarderion",
    "technorepair",
    "technodoctor",
    "technomanning",
    "technorecon",
    "technoatom",
    "technodirector",
    "technomender",
    "technoroomba",
    "technoa55",
    "blobswarm",
    "hatch",
    "spider",
    "weaver",
    "queen",
    "ancient",
    "royal",
    "traveler",
    "avatar",
    "avatara",
    "avatarroyal",
    "avatarroyala"
})
public class WhiteList {

    protected String human;
    protected String medic;
    protected String engineer;
    protected String soldier;
    protected String mfk;
    protected String detective;
    protected String tully;
    protected String jerry;
    protected String jerryg;
    protected String ponyj;
    protected String ponycj;
    protected String engi;
    protected String separatist;
    protected String separatistblur;
    protected String defend;
    protected String turzil;
    protected String energy;
    protected String monk;
    protected String bomber;
    protected String radical;
    protected String peace;
    protected String deathless;
    protected String orchid;
    protected String chieftain;
    protected String mantis;
    protected String freemantis;
    protected String suzerain;
    protected String warlord;
    protected String bishop;
    protected String rock;
    protected String outcast;
    protected String commando;
    protected String crusader;
    protected String cultist;
    protected String lord;
    protected String symbiote;
    protected String crystal;
    protected String sentinel;
    protected String ruwen;
    protected String slug;
    protected String snail;
    protected String sabo;
    protected String ranger;
    protected String sylvan;
    protected String nights;
    protected String slocknog;
    protected String shell;
    protected String shellmedic;
    protected String shellrepair;
    protected String shellguardian;
    protected String toxic;
    protected String shellalkali;
    protected String anaerobic;
    protected String welder;
    protected String eater;
    protected String augmented;
    protected String anointed;
    protected String phantom;
    protected String phantomalpha;
    protected String goul;
    protected String goulalpha;
    protected String mare;
    protected String marealpha;
    protected String wraith;
    protected String wraithalpha;
    protected String reaper;
    protected String bloblarge;
    protected String blob;
    protected String blobancient;
    protected String blobcrystal;
    protected String blobfreemantis;
    protected String blobhuman;
    protected String bloblizard;
    protected String blobmantis;
    protected String blobpony;
    protected String blobqueen;
    protected String blobrock;
    protected String blobsalt;
    protected String blobshell;
    protected String blobslug;
    protected String blobspider;
    protected String bloborchid;
    protected String techno;
    protected String technoancient;
    protected String technoengi;
    protected String technoavatar;
    protected String technolanius;
    protected String technobattle;
    protected String technobattle2;
    protected String technoboarderion;
    protected String technorepair;
    protected String technodoctor;
    protected String technomanning;
    protected String technorecon;
    protected String technoatom;
    protected String technodirector;
    protected String technomender;
    protected String technoroomba;
    protected String technoa55;
    protected String blobswarm;
    protected String hatch;
    protected String spider;
    protected String weaver;
    protected String queen;
    protected String ancient;
    protected String royal;
    protected String traveler;
    protected String avatar;
    protected String avatara;
    protected String avatarroyal;
    protected String avatarroyala;

    /**
     * Gets the value of the human property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHuman() {
        return human;
    }

    /**
     * Sets the value of the human property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHuman(String value) {
        this.human = value;
    }

    /**
     * Gets the value of the medic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedic() {
        return medic;
    }

    /**
     * Sets the value of the medic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedic(String value) {
        this.medic = value;
    }

    /**
     * Gets the value of the engineer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineer() {
        return engineer;
    }

    /**
     * Sets the value of the engineer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineer(String value) {
        this.engineer = value;
    }

    /**
     * Gets the value of the soldier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldier() {
        return soldier;
    }

    /**
     * Sets the value of the soldier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldier(String value) {
        this.soldier = value;
    }

    /**
     * Gets the value of the mfk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfk() {
        return mfk;
    }

    /**
     * Sets the value of the mfk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfk(String value) {
        this.mfk = value;
    }

    /**
     * Gets the value of the detective property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetective() {
        return detective;
    }

    /**
     * Sets the value of the detective property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetective(String value) {
        this.detective = value;
    }

    /**
     * Gets the value of the tully property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTully() {
        return tully;
    }

    /**
     * Sets the value of the tully property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTully(String value) {
        this.tully = value;
    }

    /**
     * Gets the value of the jerry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJerry() {
        return jerry;
    }

    /**
     * Sets the value of the jerry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJerry(String value) {
        this.jerry = value;
    }

    /**
     * Gets the value of the jerryg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJerryg() {
        return jerryg;
    }

    /**
     * Sets the value of the jerryg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJerryg(String value) {
        this.jerryg = value;
    }

    /**
     * Gets the value of the ponyj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPonyj() {
        return ponyj;
    }

    /**
     * Sets the value of the ponyj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPonyj(String value) {
        this.ponyj = value;
    }

    /**
     * Gets the value of the ponycj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPonycj() {
        return ponycj;
    }

    /**
     * Sets the value of the ponycj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPonycj(String value) {
        this.ponycj = value;
    }

    /**
     * Gets the value of the engi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngi() {
        return engi;
    }

    /**
     * Sets the value of the engi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngi(String value) {
        this.engi = value;
    }

    /**
     * Gets the value of the separatist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparatist() {
        return separatist;
    }

    /**
     * Sets the value of the separatist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparatist(String value) {
        this.separatist = value;
    }

    /**
     * Gets the value of the separatistblur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparatistblur() {
        return separatistblur;
    }

    /**
     * Sets the value of the separatistblur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparatistblur(String value) {
        this.separatistblur = value;
    }

    /**
     * Gets the value of the defend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefend() {
        return defend;
    }

    /**
     * Sets the value of the defend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefend(String value) {
        this.defend = value;
    }

    /**
     * Gets the value of the turzil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurzil() {
        return turzil;
    }

    /**
     * Sets the value of the turzil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurzil(String value) {
        this.turzil = value;
    }

    /**
     * Gets the value of the energy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnergy() {
        return energy;
    }

    /**
     * Sets the value of the energy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnergy(String value) {
        this.energy = value;
    }

    /**
     * Gets the value of the monk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonk() {
        return monk;
    }

    /**
     * Sets the value of the monk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonk(String value) {
        this.monk = value;
    }

    /**
     * Gets the value of the bomber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBomber() {
        return bomber;
    }

    /**
     * Sets the value of the bomber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBomber(String value) {
        this.bomber = value;
    }

    /**
     * Gets the value of the radical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadical() {
        return radical;
    }

    /**
     * Sets the value of the radical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadical(String value) {
        this.radical = value;
    }

    /**
     * Gets the value of the peace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeace() {
        return peace;
    }

    /**
     * Sets the value of the peace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeace(String value) {
        this.peace = value;
    }

    /**
     * Gets the value of the deathless property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeathless() {
        return deathless;
    }

    /**
     * Sets the value of the deathless property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeathless(String value) {
        this.deathless = value;
    }

    /**
     * Gets the value of the orchid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrchid() {
        return orchid;
    }

    /**
     * Sets the value of the orchid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrchid(String value) {
        this.orchid = value;
    }

    /**
     * Gets the value of the chieftain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChieftain() {
        return chieftain;
    }

    /**
     * Sets the value of the chieftain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChieftain(String value) {
        this.chieftain = value;
    }

    /**
     * Gets the value of the mantis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMantis() {
        return mantis;
    }

    /**
     * Sets the value of the mantis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMantis(String value) {
        this.mantis = value;
    }

    /**
     * Gets the value of the freemantis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreemantis() {
        return freemantis;
    }

    /**
     * Sets the value of the freemantis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreemantis(String value) {
        this.freemantis = value;
    }

    /**
     * Gets the value of the suzerain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuzerain() {
        return suzerain;
    }

    /**
     * Sets the value of the suzerain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuzerain(String value) {
        this.suzerain = value;
    }

    /**
     * Gets the value of the warlord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarlord() {
        return warlord;
    }

    /**
     * Sets the value of the warlord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarlord(String value) {
        this.warlord = value;
    }

    /**
     * Gets the value of the bishop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBishop() {
        return bishop;
    }

    /**
     * Sets the value of the bishop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBishop(String value) {
        this.bishop = value;
    }

    /**
     * Gets the value of the rock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRock() {
        return rock;
    }

    /**
     * Sets the value of the rock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRock(String value) {
        this.rock = value;
    }

    /**
     * Gets the value of the outcast property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutcast() {
        return outcast;
    }

    /**
     * Sets the value of the outcast property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutcast(String value) {
        this.outcast = value;
    }

    /**
     * Gets the value of the commando property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommando() {
        return commando;
    }

    /**
     * Sets the value of the commando property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommando(String value) {
        this.commando = value;
    }

    /**
     * Gets the value of the crusader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrusader() {
        return crusader;
    }

    /**
     * Sets the value of the crusader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrusader(String value) {
        this.crusader = value;
    }

    /**
     * Gets the value of the cultist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCultist() {
        return cultist;
    }

    /**
     * Sets the value of the cultist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCultist(String value) {
        this.cultist = value;
    }

    /**
     * Gets the value of the lord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLord() {
        return lord;
    }

    /**
     * Sets the value of the lord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLord(String value) {
        this.lord = value;
    }

    /**
     * Gets the value of the symbiote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbiote() {
        return symbiote;
    }

    /**
     * Sets the value of the symbiote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbiote(String value) {
        this.symbiote = value;
    }

    /**
     * Gets the value of the crystal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrystal() {
        return crystal;
    }

    /**
     * Sets the value of the crystal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrystal(String value) {
        this.crystal = value;
    }

    /**
     * Gets the value of the sentinel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentinel() {
        return sentinel;
    }

    /**
     * Sets the value of the sentinel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentinel(String value) {
        this.sentinel = value;
    }

    /**
     * Gets the value of the ruwen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuwen() {
        return ruwen;
    }

    /**
     * Sets the value of the ruwen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuwen(String value) {
        this.ruwen = value;
    }

    /**
     * Gets the value of the slug property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlug() {
        return slug;
    }

    /**
     * Sets the value of the slug property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlug(String value) {
        this.slug = value;
    }

    /**
     * Gets the value of the snail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnail() {
        return snail;
    }

    /**
     * Sets the value of the snail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnail(String value) {
        this.snail = value;
    }

    /**
     * Gets the value of the sabo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSabo() {
        return sabo;
    }

    /**
     * Sets the value of the sabo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSabo(String value) {
        this.sabo = value;
    }

    /**
     * Gets the value of the ranger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRanger() {
        return ranger;
    }

    /**
     * Sets the value of the ranger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRanger(String value) {
        this.ranger = value;
    }

    /**
     * Gets the value of the sylvan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSylvan() {
        return sylvan;
    }

    /**
     * Sets the value of the sylvan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSylvan(String value) {
        this.sylvan = value;
    }

    /**
     * Gets the value of the nights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNights() {
        return nights;
    }

    /**
     * Sets the value of the nights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNights(String value) {
        this.nights = value;
    }

    /**
     * Gets the value of the slocknog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlocknog() {
        return slocknog;
    }

    /**
     * Sets the value of the slocknog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlocknog(String value) {
        this.slocknog = value;
    }

    /**
     * Gets the value of the shell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShell() {
        return shell;
    }

    /**
     * Sets the value of the shell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShell(String value) {
        this.shell = value;
    }

    /**
     * Gets the value of the shellmedic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellmedic() {
        return shellmedic;
    }

    /**
     * Sets the value of the shellmedic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellmedic(String value) {
        this.shellmedic = value;
    }

    /**
     * Gets the value of the shellrepair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellrepair() {
        return shellrepair;
    }

    /**
     * Sets the value of the shellrepair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellrepair(String value) {
        this.shellrepair = value;
    }

    /**
     * Gets the value of the shellguardian property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellguardian() {
        return shellguardian;
    }

    /**
     * Sets the value of the shellguardian property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellguardian(String value) {
        this.shellguardian = value;
    }

    /**
     * Gets the value of the toxic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToxic() {
        return toxic;
    }

    /**
     * Sets the value of the toxic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToxic(String value) {
        this.toxic = value;
    }

    /**
     * Gets the value of the shellalkali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShellalkali() {
        return shellalkali;
    }

    /**
     * Sets the value of the shellalkali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShellalkali(String value) {
        this.shellalkali = value;
    }

    /**
     * Gets the value of the anaerobic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnaerobic() {
        return anaerobic;
    }

    /**
     * Sets the value of the anaerobic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnaerobic(String value) {
        this.anaerobic = value;
    }

    /**
     * Gets the value of the welder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWelder() {
        return welder;
    }

    /**
     * Sets the value of the welder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWelder(String value) {
        this.welder = value;
    }

    /**
     * Gets the value of the eater property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEater() {
        return eater;
    }

    /**
     * Sets the value of the eater property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEater(String value) {
        this.eater = value;
    }

    /**
     * Gets the value of the augmented property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugmented() {
        return augmented;
    }

    /**
     * Sets the value of the augmented property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugmented(String value) {
        this.augmented = value;
    }

    /**
     * Gets the value of the anointed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnointed() {
        return anointed;
    }

    /**
     * Sets the value of the anointed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnointed(String value) {
        this.anointed = value;
    }

    /**
     * Gets the value of the phantom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhantom() {
        return phantom;
    }

    /**
     * Sets the value of the phantom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhantom(String value) {
        this.phantom = value;
    }

    /**
     * Gets the value of the phantomalpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhantomalpha() {
        return phantomalpha;
    }

    /**
     * Sets the value of the phantomalpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhantomalpha(String value) {
        this.phantomalpha = value;
    }

    /**
     * Gets the value of the goul property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoul() {
        return goul;
    }

    /**
     * Sets the value of the goul property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoul(String value) {
        this.goul = value;
    }

    /**
     * Gets the value of the goulalpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoulalpha() {
        return goulalpha;
    }

    /**
     * Sets the value of the goulalpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoulalpha(String value) {
        this.goulalpha = value;
    }

    /**
     * Gets the value of the mare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMare() {
        return mare;
    }

    /**
     * Sets the value of the mare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMare(String value) {
        this.mare = value;
    }

    /**
     * Gets the value of the marealpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarealpha() {
        return marealpha;
    }

    /**
     * Sets the value of the marealpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarealpha(String value) {
        this.marealpha = value;
    }

    /**
     * Gets the value of the wraith property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWraith() {
        return wraith;
    }

    /**
     * Sets the value of the wraith property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWraith(String value) {
        this.wraith = value;
    }

    /**
     * Gets the value of the wraithalpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWraithalpha() {
        return wraithalpha;
    }

    /**
     * Sets the value of the wraithalpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWraithalpha(String value) {
        this.wraithalpha = value;
    }

    /**
     * Gets the value of the reaper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaper() {
        return reaper;
    }

    /**
     * Sets the value of the reaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaper(String value) {
        this.reaper = value;
    }

    /**
     * Gets the value of the bloblarge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloblarge() {
        return bloblarge;
    }

    /**
     * Sets the value of the bloblarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloblarge(String value) {
        this.bloblarge = value;
    }

    /**
     * Gets the value of the blob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlob() {
        return blob;
    }

    /**
     * Sets the value of the blob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlob(String value) {
        this.blob = value;
    }

    /**
     * Gets the value of the blobancient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobancient() {
        return blobancient;
    }

    /**
     * Sets the value of the blobancient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobancient(String value) {
        this.blobancient = value;
    }

    /**
     * Gets the value of the blobcrystal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobcrystal() {
        return blobcrystal;
    }

    /**
     * Sets the value of the blobcrystal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobcrystal(String value) {
        this.blobcrystal = value;
    }

    /**
     * Gets the value of the blobfreemantis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobfreemantis() {
        return blobfreemantis;
    }

    /**
     * Sets the value of the blobfreemantis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobfreemantis(String value) {
        this.blobfreemantis = value;
    }

    /**
     * Gets the value of the blobhuman property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobhuman() {
        return blobhuman;
    }

    /**
     * Sets the value of the blobhuman property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobhuman(String value) {
        this.blobhuman = value;
    }

    /**
     * Gets the value of the bloblizard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloblizard() {
        return bloblizard;
    }

    /**
     * Sets the value of the bloblizard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloblizard(String value) {
        this.bloblizard = value;
    }

    /**
     * Gets the value of the blobmantis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobmantis() {
        return blobmantis;
    }

    /**
     * Sets the value of the blobmantis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobmantis(String value) {
        this.blobmantis = value;
    }

    /**
     * Gets the value of the blobpony property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobpony() {
        return blobpony;
    }

    /**
     * Sets the value of the blobpony property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobpony(String value) {
        this.blobpony = value;
    }

    /**
     * Gets the value of the blobqueen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobqueen() {
        return blobqueen;
    }

    /**
     * Sets the value of the blobqueen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobqueen(String value) {
        this.blobqueen = value;
    }

    /**
     * Gets the value of the blobrock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobrock() {
        return blobrock;
    }

    /**
     * Sets the value of the blobrock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobrock(String value) {
        this.blobrock = value;
    }

    /**
     * Gets the value of the blobsalt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobsalt() {
        return blobsalt;
    }

    /**
     * Sets the value of the blobsalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobsalt(String value) {
        this.blobsalt = value;
    }

    /**
     * Gets the value of the blobshell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobshell() {
        return blobshell;
    }

    /**
     * Sets the value of the blobshell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobshell(String value) {
        this.blobshell = value;
    }

    /**
     * Gets the value of the blobslug property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobslug() {
        return blobslug;
    }

    /**
     * Sets the value of the blobslug property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobslug(String value) {
        this.blobslug = value;
    }

    /**
     * Gets the value of the blobspider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobspider() {
        return blobspider;
    }

    /**
     * Sets the value of the blobspider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobspider(String value) {
        this.blobspider = value;
    }

    /**
     * Gets the value of the bloborchid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloborchid() {
        return bloborchid;
    }

    /**
     * Sets the value of the bloborchid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloborchid(String value) {
        this.bloborchid = value;
    }

    /**
     * Gets the value of the techno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechno() {
        return techno;
    }

    /**
     * Sets the value of the techno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechno(String value) {
        this.techno = value;
    }

    /**
     * Gets the value of the technoancient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnoancient() {
        return technoancient;
    }

    /**
     * Sets the value of the technoancient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnoancient(String value) {
        this.technoancient = value;
    }

    /**
     * Gets the value of the technoengi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnoengi() {
        return technoengi;
    }

    /**
     * Sets the value of the technoengi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnoengi(String value) {
        this.technoengi = value;
    }

    /**
     * Gets the value of the technoavatar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnoavatar() {
        return technoavatar;
    }

    /**
     * Sets the value of the technoavatar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnoavatar(String value) {
        this.technoavatar = value;
    }

    /**
     * Gets the value of the technolanius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnolanius() {
        return technolanius;
    }

    /**
     * Sets the value of the technolanius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnolanius(String value) {
        this.technolanius = value;
    }

    /**
     * Gets the value of the technobattle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnobattle() {
        return technobattle;
    }

    /**
     * Sets the value of the technobattle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnobattle(String value) {
        this.technobattle = value;
    }

    /**
     * Gets the value of the technobattle2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnobattle2() {
        return technobattle2;
    }

    /**
     * Sets the value of the technobattle2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnobattle2(String value) {
        this.technobattle2 = value;
    }

    /**
     * Gets the value of the technoboarderion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnoboarderion() {
        return technoboarderion;
    }

    /**
     * Sets the value of the technoboarderion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnoboarderion(String value) {
        this.technoboarderion = value;
    }

    /**
     * Gets the value of the technorepair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnorepair() {
        return technorepair;
    }

    /**
     * Sets the value of the technorepair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnorepair(String value) {
        this.technorepair = value;
    }

    /**
     * Gets the value of the technodoctor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnodoctor() {
        return technodoctor;
    }

    /**
     * Sets the value of the technodoctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnodoctor(String value) {
        this.technodoctor = value;
    }

    /**
     * Gets the value of the technomanning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnomanning() {
        return technomanning;
    }

    /**
     * Sets the value of the technomanning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnomanning(String value) {
        this.technomanning = value;
    }

    /**
     * Gets the value of the technorecon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnorecon() {
        return technorecon;
    }

    /**
     * Sets the value of the technorecon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnorecon(String value) {
        this.technorecon = value;
    }

    /**
     * Gets the value of the technoatom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnoatom() {
        return technoatom;
    }

    /**
     * Sets the value of the technoatom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnoatom(String value) {
        this.technoatom = value;
    }

    /**
     * Gets the value of the technodirector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnodirector() {
        return technodirector;
    }

    /**
     * Sets the value of the technodirector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnodirector(String value) {
        this.technodirector = value;
    }

    /**
     * Gets the value of the technomender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnomender() {
        return technomender;
    }

    /**
     * Sets the value of the technomender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnomender(String value) {
        this.technomender = value;
    }

    /**
     * Gets the value of the technoroomba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnoroomba() {
        return technoroomba;
    }

    /**
     * Sets the value of the technoroomba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnoroomba(String value) {
        this.technoroomba = value;
    }

    /**
     * Gets the value of the technoa55 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnoa55() {
        return technoa55;
    }

    /**
     * Sets the value of the technoa55 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnoa55(String value) {
        this.technoa55 = value;
    }

    /**
     * Gets the value of the blobswarm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlobswarm() {
        return blobswarm;
    }

    /**
     * Sets the value of the blobswarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlobswarm(String value) {
        this.blobswarm = value;
    }

    /**
     * Gets the value of the hatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatch() {
        return hatch;
    }

    /**
     * Sets the value of the hatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatch(String value) {
        this.hatch = value;
    }

    /**
     * Gets the value of the spider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpider() {
        return spider;
    }

    /**
     * Sets the value of the spider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpider(String value) {
        this.spider = value;
    }

    /**
     * Gets the value of the weaver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeaver() {
        return weaver;
    }

    /**
     * Sets the value of the weaver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeaver(String value) {
        this.weaver = value;
    }

    /**
     * Gets the value of the queen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueen() {
        return queen;
    }

    /**
     * Sets the value of the queen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueen(String value) {
        this.queen = value;
    }

    /**
     * Gets the value of the ancient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAncient() {
        return ancient;
    }

    /**
     * Sets the value of the ancient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAncient(String value) {
        this.ancient = value;
    }

    /**
     * Gets the value of the royal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoyal() {
        return royal;
    }

    /**
     * Sets the value of the royal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoyal(String value) {
        this.royal = value;
    }

    /**
     * Gets the value of the traveler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraveler() {
        return traveler;
    }

    /**
     * Sets the value of the traveler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraveler(String value) {
        this.traveler = value;
    }

    /**
     * Gets the value of the avatar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * Sets the value of the avatar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvatar(String value) {
        this.avatar = value;
    }

    /**
     * Gets the value of the avatara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvatara() {
        return avatara;
    }

    /**
     * Sets the value of the avatara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvatara(String value) {
        this.avatara = value;
    }

    /**
     * Gets the value of the avatarroyal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvatarroyal() {
        return avatarroyal;
    }

    /**
     * Sets the value of the avatarroyal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvatarroyal(String value) {
        this.avatarroyal = value;
    }

    /**
     * Gets the value of the avatarroyala property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvatarroyala() {
        return avatarroyala;
    }

    /**
     * Sets the value of the avatarroyala property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvatarroyala(String value) {
        this.avatarroyala = value;
    }

}
