//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.15 at 05:23:14 PM EDT 
//


package net.ceshion.ftl.xml.hyperspace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hatch" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="spider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="weaver" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hatch",
    "spider",
    "weaver"
})
public class WhiteList3 {

    @XmlElement(required = true)
    protected String hatch;
    @XmlElement(required = true)
    protected String spider;
    @XmlElement(required = true)
    protected String weaver;

    /**
     * Gets the value of the hatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatch() {
        return hatch;
    }

    /**
     * Sets the value of the hatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatch(String value) {
        this.hatch = value;
    }

    /**
     * Gets the value of the spider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpider() {
        return spider;
    }

    /**
     * Sets the value of the spider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpider(String value) {
        this.spider = value;
    }

    /**
     * Gets the value of the weaver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeaver() {
        return weaver;
    }

    /**
     * Sets the value of the weaver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeaver(String value) {
        this.weaver = value;
    }

}
